package com.example.todo.model;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

/**
 * JPA entity representing a todo item and its lifecycle state.
 *
 * <p>Todos are created in OPEN state, and may transition to CLOSED or CANCELLED with remarks.
 */
@Entity
@Table(name = "todos")
public class Todo {

    /** Surrogate identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Required short title describing the task. */
    @NotBlank
    @Column(nullable = false)
    private String title;

    /** Optional long-form details for the task. */
    @Column(length = 1000)
    private String description;

    /** Required priority used for ordering and filtering. */
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Priority priority;

    /** Current lifecycle status, defaults to OPEN for new entities. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Status status = Status.OPEN;

    /** Optional remarks captured during close or cancel operations. */
    @Column(length = 1000)
    private String remarks;

    /** Creation timestamp set once during initial persistence. */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Last update timestamp refreshed on each update. */
    private LocalDateTime updatedAt;

    /** Initializes entity timestamps before first insert. */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /** Refreshes update timestamp before each entity update. */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    public Todo() {}

    public Todo(String title, String description, Priority priority) {
        this.title = title;
        this.description = description;
        this.priority = priority;
        this.status = Status.OPEN;
    }

    public Long getId() { return id; }
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    public Priority getPriority() { return priority; }
    public void setPriority(Priority priority) { this.priority = priority; }
    public Status getStatus() { return status; }
    public void setStatus(Status status) { this.status = status; }
    public String getRemarks() { return remarks; }
    public void setRemarks(String remarks) { this.remarks = remarks; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public LocalDateTime getUpdatedAt() { return updatedAt; }
}
